name: Deploy to VDS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VDS
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
         cd /var/www/1337community.com
          git pull
          cd backend && npm install && pm2 restart backend
          cd ../frontend && npm install && npm run build
          sudo nginx -s reload