name: Deploy to VDS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VDS
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/1337community.com
          echo "🚀 Начинаем развертывание..."
          
          # Обновление кода из GitHub
          echo "📦 Обновление кода..."
          git pull
          
          # Остановка и удаление старых процессов PM2
          echo "⏹️ Остановка backend процесса..."
          pm2 stop 1337-backend || true
          pm2 delete 1337-backend || true
          
          # Установка корневых зависимостей
          echo "📋 Установка корневых зависимостей..."
          npm install
          
          # Backend: установка зависимостей и запуск
          echo "🔧 Настройка backend..."
          cd backend && npm install
          pm2 start server.js --name "1337-backend"
          echo "✅ Backend запущен"
          
          # Frontend: установка зависимостей с обходом конфликтов версий
          echo "🎨 Настройка frontend..."
          cd ../frontend
          
          # Установка зависимостей с флагом для обхода конфликтов React версий
          echo "📦 Установка зависимостей frontend (с --legacy-peer-deps)..."
          npm install --legacy-peer-deps
          
          # Проверка успешности установки
          if [ $? -eq 0 ]; then
            echo "✅ Зависимости frontend установлены успешно"
            
            # Сборка production версии
            echo "🔨 Сборка frontend..."
            npm run build
            
            if [ $? -eq 0 ]; then
              echo "✅ Frontend собран успешно"
            else
              echo "❌ Ошибка сборки frontend"
              exit 1
            fi
          else
            echo "❌ Ошибка установки зависимостей frontend"
            exit 1
          fi
          
          # Перезапуск Nginx
          echo "🔄 Перезапуск Nginx..."
          sudo nginx -s reload
          
          # Проверка статуса сервисов
          echo "📊 Проверка статуса сервисов..."
          pm2 status
          
          echo "🎉 Развертывание завершено успешно!"
          echo "🛡️ Rich Text редактор готов к использованию!"
