name: Deploy to VDS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VDS
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: 80.87.200.23
        username: root
        key: 01012006Fortnite!
        script: |
          cd /var/www/1337community.com
          git pull --merge
          cd backend && npm install && pm2 restart backend
          cd ../frontend && npm install && npm run build
          sudo nginx -s reload